### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [bikbaev/kottans-js-2016#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить
```html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```

**Comment by bikbaev** [comment]
first task is done

**Comment by mkozhukharenko** [comment]
please, refactor your commit message from this "first task" to this "#2 first task". And add a link to the task

**Comment by mkozhukharenko** [comment]
I see here two separate sections:
```
		<ul>
			<li><a href="https://tmfeed.ru/#/">TM Feed</a></li>
			<li><a href="https://habrahabr.ru/">Хабрахабр</a></li>
			<li><a href="geektimes.ru">Geektimes</a></li>
			<li><a href="toster.ru">Тостер</a></li>
			<p>Спецпроекты:</p>
			<li><a href="http://contests.techdays.ru/bizSpark5accounts/?utm_source=habrahabr&utm_medium=landing&utm_campaign=ms1">Собери стартап</a></li>
			<li><a href="http://www.linuxloves.ru/">Сценарии для Linux</a></li>
			<li><a href="https://special.habrahabr.ru/microsoft/unity/">Создайте первую игру</a></li>
		</ul>
```

**Comment by mkozhukharenko** [comment]
I'd add a figurecaption:

```html
		<figure>
			<ul>
				<li><a href="#"><img src="images/user_photo.png"></a></li>
				<li><a href="#">user_name</a><br>Пользователь</li>
				<li>2.0<br>Карма</li>
				<li>0.0<br>Рейтинг</li>
			</ul>
		</figure>
```
And you can move out Карма & Рейтинг from a figure

I'w use more complex markup for this. 
```html
<li>2.0<br>Карма</li>
```

**Comment by mkozhukharenko** [comment]
move `<base target="_blank"></base>` to the header

**Comment by mkozhukharenko** [comment]
check you markup [here](https://validator.w3.org/nu)
there are a lot of errors! 😕

**Comment by mkozhukharenko** [comment]
👍  each section has a header

**Comment by mkozhukharenko** [comment]
```html
		<aside>
			<ul>
				<li><h1>Интересные публикации</h1></li>
				<li><input type="radio">Хабрахабр</li>
				<li><input type="radio">Гиктаймс</li>
			</ul>
			<ul>
				<li><img src="images/geektimes.jpg"> <a href="#">Установлены особенности людей, которые...</a><img src="images/comments.png">7</li>
				<li><img src="images/logo_small.png"> <a href="#">Опыт перехода сайта на...</a><img src="images/comments.png">16</li>
			</ul>
		</aside>
```
I'd split it into two sections

**Comment by bikbaev** [comment]
[#2](https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html) first task

**Comment by bikbaev** [comment]
I tried to fix all errors that you tell. But validator still thinks that there are faults. For example, there are some sections and articles without headings, but there aren't headings for them in original page and I didn't want to use div-s

**Comment by mkozhukharenko** [comment]
I'd make it aside. 

```html

	<header>
		<base target="_blank"></base>
		<section>
			<ul>
				<li><a href="https://tmfeed.ru/#/">TM Feed</a></li>
				<li><a href="https://habrahabr.ru/">Хабрахабр</a></li>
				<li><a href="geektimes.ru">Geektimes</a></li>
				<li><a href="toster.ru">Тостер</a></li>
			</ul>
		</section>
		<section>
			<p>Спецпроекты:</p>
			<ul>
				<li><a href="http://contests.techdays.ru/bizSpark5accounts/?utm_source=habrahabr&utm_medium=landing&utm_campaign=ms1">Собери стартап</a></li>
				<li><a href="http://www.linuxloves.ru/">Сценарии для Linux</a></li>
				<li><a href="https://special.habrahabr.ru/microsoft/unity/">Создайте первую игру</a></li>
			</ul>
		</section>
	</header>

```

Watch the html2 video from a course , @shvaikalesh told about that

**Comment by mkozhukharenko** [comment]
validator is telling that it's wrong. 
He may be right 😄 
```html
<footer>
		<small>
			<ul>
```

**Comment by mkozhukharenko** [comment]
this section should be in nav
```html
			<section>
				<h1>Спецпроекты</h1>
				<ul>
					<li><a href="#">Соберите свой стартап</a></li>
					<li><a href="#">Linux в Azure</a></li>
					<li><a href="#">Создай игру</a></li>
				</ul>
			</section>
```

Have your read this [article](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external)? You had too 😺

**Comment by mkozhukharenko** [comment]
Lets have an experiments:
```html
<aside>
			<ul>
				<li><a href="#"><b>Профиль</b></a></li>
				<li><a href="#"><b>1 <br> Публикации</b></a></li>
```
it look like a buttons, isn't it? try to add a keyboard control to that elements. Lets see how it will work.

**Comment by mkozhukharenko** [comment]
> For example, there are some sections and articles without headings

You can add hidden headings

**Comment by mkozhukharenko** [comment]
```html
<section>
				<ul>
					<li><p>Интересные публикации</p></li>
					<li><input type="radio">Хабрахабр</li>
```
I'm guessing that 'Интересные публикации' is a heading here. But not sure.

**Comment by shvaikalesh** [comment]
https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L12-L28

remove sections
base is metadata only
escape amps

https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L65

article here

https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L70

meters here

https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L96-L107

remove small

https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L145-L161

section here

https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L265

small is phrasing content, ul is flow, you can not nest them

**Comment by bikbaev** [comment]
maybe "shouldn't"? And what about "sections aren't wrappers"? If I have a
part of an article with separative sense and with heading, I use a
"section" tag. And what should I do to change style of this block? To use
an extra tag "div" as wrapper?
<div>
      <section>
              ......
      </section>
</div>

2016-05-23 9:24 GMT+03:00 Nikolay <notifications@github.com>:

**Comment by mkozhukharenko** [comment]
@bikbaev,
> maybe "shouldn't"?

 you a right, I meant this section shouldn't be inside a nav because it isn't a part of a page navigation 

> To use an extra tag "div" as wrapper?

You can use a div as a wrapper because 

>  "sections aren't wrappers"

**Comment by bikbaev** [comment]
Can you advice me something to read about "onkeydown"?
<a href="#" onkeydown="location.href='
https://mail.google.com/mail/u/0/#inbox/154d317ebe00e3ea';"><b>Профиль</b></a>
- doesn't work
<input type="text" value="Profile" onkeydown="location.href='
https://mail.google.com/mail/u/0/#inbox/154d317ebe00e3ea';"></input> - works
And I can't find smth about how can I solve it

2016-05-23 13:01 GMT+03:00 Nikolay <notifications@github.com>:

**Comment by mkozhukharenko** [comment]
@bikbaev what do you want to achieve by doing this? Can you describe a problem ?

**Comment by bikbaev** [comment]
I don't understand what does it mean "a keyboard control to that elements"
towards "a" element. If I press any key when the mouse cursor on "a" I'll
go to link. But it's quite absurdly because it's an "a"-element and I can
click on it.

2016-05-23 14:59 GMT+03:00 Nikolay <notifications@github.com>:

**Comment by mkozhukharenko** [comment]
[Using the button role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role)
@shvaikalesh told about that on the lesson.

**Comment by bikbaev** [comment]
[Shvaika Aleksey](https://github.com/shvaikalesh) commented:
https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html#L12-L28
remove sections

And you advised me to add sections there. What will be better to do?

**Comment by bikbaev** [comment]
[#2](https://github.com/bikbaev/kottans-js-2016/blob/master/week01/habrahabr/habr.html) first task
